apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-example
  namespace: chaos-mesh
spec:
  action: container-kill
  mode: one
  containerNames: ['nginx']
  selector:
    namespaces:
      - chaos-test
    labelSelectors:
      'app': 'nginx'