apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: chaos-test
spec:
  template:
    spec:
      containers:
        - image: notannginximage
          imagePullPolicy: Always
          name: nginx
          resources:
            requests:
              memory: 50M
